config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :people
  resources :locations
  resources :affiliations
  
  
  namespace :api do
    namespace :v1 do
      resources :people
    end
  end


end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
    has_many :person_affiliations, dependent: :destroy
    has_many :person, through: :person_affiliations
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  before_action :set_affiliation, only: %i[ show edit update destroy ]

  # GET /affiliations or /affiliations.json
  def index
    @affiliations = Affiliation.all
  end

  # GET /affiliations/1 or /affiliations/1.json
  def show
  end

  # GET /affiliations/new
  def new
    @affiliation = Affiliation.new
  end

  # GET /affiliations/1/edit
  def edit
  end

  # POST /affiliations or /affiliations.json
  def create
    @affiliation = Affiliation.new(affiliation_params)

    respond_to do |format|
      if @affiliation.save
        format.html { redirect_to affiliation_url(@affiliation), notice: "Affiliation was successfully created." }
        format.json { render :show, status: :created, location: @affiliation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliations/1 or /affiliations/1.json
  def update
    respond_to do |format|
      if @affiliation.update(affiliation_params)
        format.html { redirect_to affiliation_url(@affiliation), notice: "Affiliation was successfully updated." }
        format.json { render :show, status: :ok, location: @affiliation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliations/1 or /affiliations/1.json
  def destroy
    @affiliation.destroy

    respond_to do |format|
      format.html { redirect_to affiliations_url, notice: "Affiliation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def affiliation_params
      params.require(:affiliation).permit(:name)
    end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/_affiliation.html.erb
<div id="<%= dom_id affiliation %>">
  <p>
    <strong>Name:</strong>
    <%= affiliation.name %>
  </p>

</div>

app/views/affiliations/_form.html.erb
<%= form_with(model: affiliation) do |form| %>
  <% if affiliation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(affiliation.errors.count, "error") %> prohibited this affiliation from being saved:</h2>

      <ul>
        <% affiliation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/affiliations/edit.html.erb
<h1>Editing affiliation</h1>

<%= render "form", affiliation: @affiliation %>

<br>

<div>
  <%= link_to "Show this affiliation", @affiliation %> |
  <%= link_to "Back to affiliations", affiliations_path %>
</div>

app/views/affiliations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Affiliations</h1>

<div id="affiliations">
  <% @affiliations.each do |affiliation| %>
    <%= render affiliation %>
    <p>
      <%= link_to "Show this affiliation", affiliation %>
    </p>
  <% end %>
</div>

<%= link_to "New affiliation", new_affiliation_path %>

app/views/affiliations/new.html.erb
<h1>New affiliation</h1>

<%= render "form", affiliation: @affiliation %>

<br>

<div>
  <%= link_to "Back to affiliations", affiliations_path %>
</div>

app/views/affiliations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @affiliation %>

<div>
  <%= link_to "Edit this affiliation", edit_affiliation_path(@affiliation) %> |
  <%= link_to "Back to affiliations", affiliations_path %>

  <%= button_to "Destroy this affiliation", @affiliation, method: :delete %>
</div>